### ISSUE TITLE
Investigate restructure of files

### ISSUE THREAD

**Issue by Pinpickle** [Pinpickle/tight#4]
@Boorj, when discussing a Yeoman generator for Bolt, [brought up a custom implementation](https://github.com/bolt/bolt/issues/3755#issuecomment-118707030) that differs from the default Bolt file structure. This sounds like a step in the right direction and, for sites like this (built with one theme, a custom local extension, for example) would help reduce file system cruft.

Here's what I'm thinking at the moment as a potential structure, I don't know how possible this is.

``` yml
app:
 - config # Includes all ordinary config as well as theme config.yml
 - cache
 - db
extensions:
# Same as current extensions folder
extension:
 - Extension.php
 - TwigHelper.php # And any other extension stuff
assets:
 - scripts
 - styles
 - images
 - fonts # etc... same as theme assets
# -- Potentially under a custom web directory -- #
files:
# Same as current files folder
assets-dist:
# Compiled versions of assets and all that
extensions:
# Public facing extensions files if under a custom web directory
# -- End: Potentially under a custom web directory -- #
.editorconfig
.env
.gitignore
.htaccess
.composer.json
composer.lock
favicon.ico
gulpfile.js # Note: Only one gulpfile instead of two!
index.php # Will have to have custom bootstrapping to make this work
package.json
README.md
```

All of the relevant asset stuff (templates, assets), should also be able to serve backend content. If the bootstrapping logic gets too complex, it may make sense to move it to a Composer package so updating is easy.
